### ISSUE TITLE
Thead gets converted to tr inside tbody instead.

### ISSUE THREAD

**Issue by backup-user19961996** [zzxming/quill-table#8]
Hi,

Thank you for this amazing library. I am noticing this issue where thead gets converted to tr inside tbody instead.

Example: 
"
thead
tr
th
Ranking
/th
th
Tool Name
/th
th
/tr
thead
"
will get converted to:
"
tbody
tr
td
RankingToolName
/td
/tr
tbody
"

Github doesn't allow me to type in HTML.

**Comment by zzxming** [comment]
yes, this module can't recognize `thead` and `tfoot`. I think `thead` can be replace by the first row in `tbody`. It's just semantic different

**Comment by backup-user19961996** [comment]
@zzxming Thank you. If I want to make it recognize ```thead```, how much efforts would it be if I were to fork and make the change myself?

**Comment by zzxming** [comment]
I guess just need add two formats to handle `th` and `thead`. and update `th` like update `col` in method `appendCol` and `removeCol`.
this version still has some bugs. I'm  refactoring code to fix them. probably finish in next week. you can start at next version

**Comment by zzxming** [comment]
@backup-user19961996 Hi. A new version has been released. You can fork and make some modifications to meet your needs.
